[package]
name = "shotgun-rs"
version = "0.1.0"
authors = ["Owen Nelson <onelson@laika.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
log = "0.4.6"
reqwest = { version ="0.9.15", default-features = false }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1.26"

[dev-dependencies]
rpassword = "3.0.2"
tokio = "0.1.18"
prettytable-rs = "0.8.0"

[features]
default = ["native-tls"]

native-tls = ["reqwest/default-tls"]
native-tls-vendored = ["reqwest/default-tls-vendored"]
rustls = ["reqwest/rustls-tls"]
